version: '3'

services:
  llama-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: unless-stopped
    volumes:
      # Для сохранения данных между перезапусками
      - ./data:/app/data
      - ./tfidf_data:/app/tfidf_data

    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - MODEL_NAME=${MODEL_NAME}
      - TEMPERATURE=${TEMPERATURE}
      - INDEX_NAME=${INDEX_NAME}
      - PINECONE_API_KEY=${PINECONE_API_KEY}

volumes:
  chatbot_data:
    driver: local