# -*- coding: utf-8 -*-
"""topic_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rE6RbcS-D4dGkAPGD8LUv-N6RjVG-HR
"""

# topic_model.py

import json
import os
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Загружаем темы
TOPICS_PATH = os.path.join(os.path.dirname(__file__), "topics.json")

def load_topics():
    with open(TOPICS_PATH, "r", encoding="utf-8") as f:
        raw_topics = json.load(f)
        return {int(k): v for k, v in raw_topics.items()}

TOPICS = load_topics()

# Подготовим список всех синонимов и мапу topic_code
SYNONYMS = []
SYNONYM_TO_TOPIC = {}

for topic_code, synonyms in TOPICS.items():
    for synonym in synonyms:
        SYNONYMS.append(synonym)
        SYNONYM_TO_TOPIC[synonym] = topic_code

# Загружаем sentence-transformers модель
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# Векторизуем все синонимы заранее
synonym_embeddings = model.encode(SYNONYMS)
print(f"Загружено {len(SYNONYMS)} синонимов по {len(TOPICS)} темам.")