# -*- coding: utf-8 -*-
"""topic_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rE6RbcS-D4dGkAPGD8LUv-N6RjVG-HR
"""

# topic_model.py

import requests
import joblib
import io
import numpy as np
from bertopic import BERTopic

MODEL_URL = 'https://storage.yandexcloud.net/cyrilos/red_bertopic_model'

def load_topic_model():
    response = requests.get(MODEL_URL)
    if response.status_code == 200:
        loaded_model = joblib.load(io.BytesIO(response.content))
        print("BERTopic модель успешно загружена.")
        return loaded_model
    else:
        raise ValueError(f"Ошибка загрузки модели: {response.status_code}")

# Загружаем один раз, чтобы не повторять загрузку при каждом запросе
topic_model = load_topic_model()