
services:
  llama-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./tfidf_data:/app/tfidf_data
      - .env:/app/.env          # ✅ если .env используется
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      MODEL_NAME: ${MODEL_NAME}
      TEMPERATURE: ${TEMPERATURE}
      INDEX_NAME: ${INDEX_NAME}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
    command: >
      sh -c "export $(grep -v '^#' .env | xargs) &&
             streamlit run app.py --server.address=0.0.0.0"

